# Configurations
title:            Tài liệu ToMoi
longtitle:        Tài liệu ToMoi - Nền tảng học tập trực tuyến hàng đầu
author:           ToMoi Team
email:            support@tomoi.vn
description: >
  Trang tài liệu chính thức của ToMoi với thiết kế hiện đại và thân thiện người dùng.
  Hướng dẫn đầy đủ về cách sử dụng nền tảng học tập trực tuyến ToMoi.

version:          1.0
gitbook_version:  3.2.3

url:              'https://docs.tomoi.vn'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

# SEO settings
lang: vi
locale: vi_VN
logo: /assets/gitbook/images/logo.png
twitter:
  username: tomoivn
  card: summary_large_image
facebook:
  publisher: https://www.facebook.com/tomoivn
social:
  name: ToMoi
  links:
    - https://www.facebook.com/tomoivn
    - https://twitter.com/tomoivn
    - https://www.instagram.com/tomoivn
    - https://www.youtube.com/tomoivn

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:title/

# Disqus comments
# disqushandler:            sighingnow

# Google Analytics
google_analytics:         UA-XXXXXXXX-X

# Website verification
webmaster_verifications:
  google: YOUR_VERIFICATION_CODE
  bing: YOUR_VERIFICATION_CODE

exclude:
  - _drafts
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others

page_width: 900px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-seo-tag 
  - jekyll-sitemap
  - jemoji
