[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.4.3"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# HTTP response headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com; img-src 'self' data: https://www.google-analytics.com; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; connect-src 'self' https://www.google-analytics.com; frame-src 'self'; frame-ancestors 'none'"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://tomoi-docs.netlify.app/*"
  to = "https://docs.tomoi.vn/:splat"
  status = 301
  force = true

# Redirect trailing slashes
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 