[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"

[[plugins]]
  package = "@netlify/plugin-sitemap"

# HTTP response headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data:;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://tomoi-docs.netlify.app/*"
  to = "https://docs.tomoi.vn/:splat"
  status = 301
  force = true

# Redirect trailing slashes
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 